### PR TITLE
Updated CDN URL

### PR DESCRIPTION
**Pull request by jimaek**
https://github.com/yahoo/pure-site/issues/376
https://github.com/yahoo/pure/issues/656

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by redonkulus** [comment]
@jimaek Thanks for the PR. Please sign the CLA and I can merge?

**Comment by jimaek** [comment]
I signed it, but the status here didnt update.

**Comment by redonkulus** [comment]
No problem, will probably kick in later. Will merge now. Thanks!

**Comment by redonkulus** [comment]
@jimaek its live now https://purecss.io/customize/

**Comment by fmp777** [comment]
OK - link fixed, but you might want to remove the COMBO status - since the repo is not fixed with jsdelivr and they still think the max version is 0.6.2 http://www.jsdelivr.com/?query=pure - so while the full pure-min.css file you linked is working its not really updated with jsdelivr so that it can do combo linking

**Pull request merged**
