### PR TITLE
add note on use with AMP

### PR DESCRIPTION
**Pull request by tycho01**
Prior discussion can be found at https://github.com/yahoo/pure/issues/675.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by tycho01** [comment]
okay, signed the CLA now. still seeing a red cross over here, so it may still need a bit of time to process it I guess.

**Comment by redonkulus** [comment]
This is live now https://purecss.io/customize/#using-pure-with-google-amp

**Comment by tycho01** [comment]
Thanks! :)

**Pull request merged**
