### PR TITLE
Update ui.js menu functionality on mobile

### PR DESCRIPTION
**Pull request by Frozenfire92**
This pull request adds the ability to click off of the side menu to close it.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by Frozenfire92** [comment]
Agreed to CLA

**Comment by jamesalley** [comment]
Great tweak to pure-site. Don't worry about the CLA, it will resolve itself eventually.

**Comment by jamesalley** [comment]
I just checked to see if there were any CLA requests which failed, but I don't see any which I need to re-submit. I'll check again tomorrow.

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by jamesalley** [comment]
OK. This pull request is looking good. Thanks for the contribution!

**Comment by redonkulus** [comment]
Been a while but tested this locally, works great. Merging...

**Pull request merged**
